#!/usr/bin/env node
/**
 * Generate README.md from the docs in `docs/`.
 *
 * The docs are the single source of truth. This assembles a polished README —
 * badges, an AI-agent block, install + quickstart (pulled from the doc pages), a
 * documentation table, and a testing section — so the README never drifts.
 *
 * Run after editing anything under `docs/`:
 *
 *     node scripts/gen-readme.mjs   (or: npm run gen:readme)
 *
 * CI (`.github/workflows/test.yml`) re-runs it and asserts no diff. Idempotent.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DOCS = join(ROOT, "docs");

const OWNER = "shipeasy-ai";
const REPO = "sdk";
const PKG = "@shipeasy/sdk";
const BLOB = `https://github.com/${OWNER}/${REPO}/blob/main`;
const PAGES_SITE = `https://${OWNER}.github.io/${REPO}`;

const PAGE_TITLE = {
  overview: "Overview",
  installation: "Installation",
  configuration: "Configuration",
  flags: "Feature flags",
  configs: "Dynamic configs",
  killswitches: "Kill switches",
  experiments: "Experiments",
  i18n: "Internationalization",
  "error-reporting": "Error reporting",
  testing: "Testing",
  openfeature: "OpenFeature",
  advanced: "Advanced",
};
const PAGE_BLURB = {
  overview: "The `configure()` + `new Client(user)` model.",
  installation: "Install, frameworks (Next / Express / Workers), `configure()` wiring.",
  configuration: "Keys, `attributes`, one-shot vs poll, every option.",
  flags: "`getFlag`, `getFlagDetail`, defaults.",
  configs: "`getConfig`, typed decode, defaults.",
  killswitches: "`getKillswitch`, named switches.",
  experiments: "`getExperiment`, `logExposure`, `track`.",
  i18n: "SSR bootstrap + i18n loader tags.",
  "error-reporting": "`see()` structured error reporting.",
  testing: "`configureForTesting` / `configureForOffline`, overrides.",
  openfeature: "`ShipeasyProvider` (OpenFeature server provider).",
  advanced: "Anon-id middleware, private attributes, sticky bucketing, SSR.",
};

const read = (rel) => readFileSync(join(DOCS, rel), "utf8");

/** Rewrite relative `(page.md)` links (as they appear inside docs/pages/) to
 *  absolute GitHub blob URLs so pulled prose links work from the repo root. */
function absolutize(text) {
  return text.replace(
    /\]\((?!https?:\/\/|\/)([\w./-]+?\.md)(#[\w-]+)?\)/g,
    (_m, p, hash) => `](${BLOB}/docs/pages/${p}${hash || ""})`,
  );
}

function firstCode(md, lang) {
  const m = md.match(new RegExp("```" + lang + "\\n([\\s\\S]*?)```"));
  return m ? m[1].replace(/\s+$/, "") : "";
}

/** First real paragraph after the H1, kept as Markdown. */
function leadParagraphMd(md) {
  const out = [];
  let started = false;
  for (const ln of md.split("\n")) {
    if (!started) {
      started = ln.startsWith("# ");
      continue;
    }
    const s = ln.trim();
    if (s === "") {
      if (out.length) break;
      continue;
    }
    if (/^[#`>|\-<]/.test(s)) {
      if (out.length) break;
      continue;
    }
    out.push(s);
  }
  return out.join(" ").replace(/\s+/g, " ").trim();
}

function leadParagraph(md) {
  return leadParagraphMd(md)
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\[(.+?)\]\([^)]*\)/g, "$1")
    .trim();
}

function main() {
  const manifest = JSON.parse(read("manifest.json"));
  const pages = manifest.pages;
  const sdk = manifest.sdk;

  const install = firstCode(read("pages/installation.md"), "bash") || `npm install ${PKG}`;
  const quickstart = firstCode(read("pages/overview.md"), "ts");
  const testingMd = read("pages/testing.md");
  const testingLead = absolutize(leadParagraphMd(testingMd));
  const testingCode = firstCode(testingMd, "ts");

  const rows = [];
  for (const key of Object.keys(pages)) {
    const title = PAGE_TITLE[key] ?? key.replace(/-/g, " ");
    let blurb = PAGE_BLURB[key] ?? leadParagraph(read(pages[key]));
    if (blurb.length > 90) blurb = blurb.slice(0, 87).trimEnd() + "…";
    rows.push(`| [${title}](${BLOB}/docs/pages/${key}.md) | ${blurb} |`);
  }
  const docsTable = rows.join("\n");

  const readme = `<!--
  This file is GENERATED by scripts/gen-readme.mjs from docs/.
  Do NOT edit by hand — edit the docs, then run: npm run gen:readme
-->

# @shipeasy/sdk (TypeScript)

[![Tests](https://github.com/${OWNER}/${REPO}/actions/workflows/test.yml/badge.svg)](https://github.com/${OWNER}/${REPO}/actions/workflows/test.yml)
[![npm](https://img.shields.io/npm/v/${PKG}.svg)](https://www.npmjs.com/package/${PKG})
[![node](https://img.shields.io/node/v/${PKG}.svg)](https://www.npmjs.com/package/${PKG})

The Shipeasy SDK for **feature flags, dynamic configs, kill switches, A/B
experiments, metric tracking, and SSR/i18n** — for Node, Next.js, and Cloudflare
Workers. Server-key only on the server; the browser uses its own client key.

> 📚 **Full documentation:** **<${PAGES_SITE}/>** — also browsable under
> [\`docs/\`](${BLOB}/docs). This README is generated from those docs.

## 🤖 Using an AI agent?

This SDK ships an installable **agent skill** — a copy-paste-ready guide to
\`configure()\` + \`new Client(user)\`, testing, experiments, error reporting, and
more, with links the agent can pull for deeper docs:

- **Skill:** [\`docs/skill/SKILL.md\`](${BLOB}/docs/skill/SKILL.md) · raw:
  \`${PAGES_SITE}/skill/SKILL.md\`
- **Install it** (ships with the package — no network):
  \`npx shipeasy-skill install\` → \`.claude/skills/shipeasy-${sdk}/SKILL.md\`
  (or via the Shipeasy CLI: \`shipeasy docs skill --sdk ${sdk} --install\`)

**Humans:** you can copy that skill straight into your own project's agent skills
directory (e.g. \`.claude/skills/shipeasy-${sdk}/SKILL.md\`) so your coding agent
always uses the correct Shipeasy patterns. Every doc page and snippet is also
fetchable by URL — start from the manifest at \`${PAGES_SITE}/manifest.json\`.

## Install

\`\`\`bash
${install}
\`\`\`

Per-framework setup (Next.js / Express / Cloudflare Workers) and the anon-id
middleware are on the [Installation](${BLOB}/docs/pages/installation.md) page.

## Quickstart — \`configure()\` once, then \`new Client(user)\` per request

\`\`\`ts
${quickstart}
\`\`\`

Constructing \`new Client(user)\` before \`configure()\` throws.

## Documentation

| Page | What |
| --- | --- |
${docsTable}

Copy-paste snippets live under [\`docs/snippets/\`](${BLOB}/docs/snippets)
(release · metrics · i18n · ops); an installable agent skill is at
[\`docs/skill/SKILL.md\`](${BLOB}/docs/skill/SKILL.md).

## Testing

${testingLead}

\`\`\`ts
${testingCode}
\`\`\`

More — the on-the-spot override helpers and a working example snapshot file — on
the [Testing](${BLOB}/docs/pages/testing.md) page.

## License

See [LICENSE](${BLOB}/LICENSE). Evaluation is tested against the cross-language
MurmurHash3 vectors in \`experiment-platform/04-evaluation.md\`.
`;

  writeFileSync(join(ROOT, "README.md"), readme);
  process.stdout.write(
    `Wrote README.md (${readme.length} bytes) from ${Object.keys(pages).length} doc pages.\n`,
  );
}

main();
